// Canonical list of IANA timezone identifiers for all FieldCore timezone selectors.
// Shared between BusinessSettings and JobForm so the list stays in sync.
export const TIMEZONES = [
  // ── United States ──
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Phoenix',
  'America/Anchorage',
  'Pacific/Honolulu',
  // ── Canada ──
  'America/Halifax',
  'America/Toronto',
  'America/Winnipeg',
  'America/Edmonton',
  'America/Vancouver',
  'America/St_Johns',
  // ── Mexico & Central America ──
  'America/Mexico_City',
  'America/Tijuana',
  'America/Cancun',
  'America/Guatemala',
  'America/Costa_Rica',
  'America/Tegucigalpa',
  // ── Caribbean ──
  'America/Puerto_Rico',
  'America/Jamaica',
  'America/Nassau',
  // ── South America ──
  'America/Bogota',
  'America/Lima',
  'America/Caracas',
  'America/La_Paz',
  'America/Santiago',
  'America/Buenos_Aires',
  'America/Sao_Paulo',
  'America/Manaus',
  'America/Asuncion',
  'America/Montevideo',
  // ── Europe ──
  'Europe/London',
  'Europe/Dublin',
  'Europe/Lisbon',
  'Atlantic/Reykjavik',
  'Europe/Paris',
  'Europe/Berlin',
  'Europe/Madrid',
  'Europe/Rome',
  'Europe/Amsterdam',
  'Europe/Brussels',
  'Europe/Zurich',
  'Europe/Vienna',
  'Europe/Prague',
  'Europe/Warsaw',
  'Europe/Budapest',
  'Europe/Stockholm',
  'Europe/Oslo',
  'Europe/Copenhagen',
  'Europe/Helsinki',
  'Europe/Athens',
  'Europe/Bucharest',
  'Europe/Sofia',
  'Europe/Kiev',
  'Europe/Minsk',
  'Europe/Moscow',
  'Europe/Istanbul',
  // ── Africa ──
  'Africa/Abidjan',
  'Africa/Lagos',
  'Africa/Accra',
  'Africa/Nairobi',
  'Africa/Cairo',
  'Africa/Casablanca',
  'Africa/Johannesburg',
  'Africa/Addis_Ababa',
  'Africa/Dar_es_Salaam',
  'Africa/Khartoum',
  'Africa/Tunis',
  // ── Middle East ──
  'Asia/Dubai',
  'Asia/Riyadh',
  'Asia/Kuwait',
  'Asia/Baghdad',
  'Asia/Beirut',
  'Asia/Jerusalem',
  'Asia/Muscat',
  'Asia/Qatar',
  'Asia/Tehran',
  // ── South & Central Asia ──
  'Asia/Karachi',
  'Asia/Kolkata',
  'Asia/Colombo',
  'Asia/Dhaka',
  'Asia/Kathmandu',
  'Asia/Tashkent',
  'Asia/Almaty',
  'Asia/Kabul',
  // ── East Asia ──
  'Asia/Shanghai',
  'Asia/Hong_Kong',
  'Asia/Tokyo',
  'Asia/Seoul',
  'Asia/Singapore',
  'Asia/Taipei',
  'Asia/Kuala_Lumpur',
  'Asia/Bangkok',
  'Asia/Ho_Chi_Minh',
  'Asia/Jakarta',
  'Asia/Manila',
  'Asia/Yangon',
  'Asia/Rangoon',
  // ── Oceania ──
  'Australia/Sydney',
  'Australia/Melbourne',
  'Australia/Brisbane',
  'Australia/Perth',
  'Australia/Adelaide',
  'Australia/Darwin',
  'Australia/Hobart',
  'Pacific/Auckland',
  'Pacific/Fiji',
  'Pacific/Guam',
  'Pacific/Port_Moresby',
  'Pacific/Apia',
];
